#配置服务名称
spring:
  application:
    name: consumer-service
server:
  port: 8765
#配置注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#Feign是自带断路器的，在D版本的Spring Cloud之后，它没有默认打开。需要在配置文件中配置打开它，在配置文件加以下代码：
feign:
  hystrix:
    enabled : true