#8268 8269
server:
  port: 8268

spring:
  application:
    name: zuul-service

#注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#路由策略配置
#以/api-a/ 开头的请求都转发给ribbon-service服务；
#以/api-b/开头的请求都转发给consumer-service服务；
#/api-a/、/api-b/将代替请求url中的服务名，增加安全性
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: ribbon-service
    api-b:
      path: /api-b/**
      serviceId: consumer-service
  prefix: /zl #统一前缀  注意事项：统一前缀切勿设置zuul关键字，否则请求无法到达
  ignored-services: "*" #屏蔽服务名,过滤直接拿consumer-service服务名访问的请求
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000

#zuul负载均衡
ribbon:
  ConnectionTimeout: 500
  ReadTimeout: 2000