
#\u914D\u7F6E\u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769

spring:
  application:
    name: zuul-service
#\u914D\u7F6E\u8DEF\u7531
#\u4EE5/api-a/ \u5F00\u5934\u7684\u8BF7\u6C42\u90FD\u8F6C\u53D1\u7ED9ribbon-service\u670D\u52A1\uFF1B
#\u4EE5/api-b/\u5F00\u5934\u7684\u8BF7\u6C42\u90FD\u8F6C\u53D1\u7ED9consumer-service\u670D\u52A1\uFF1B
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: ribbon-service
    api-b:
      path: /api-b/**
      serviceId: consumer-service