
#eureka-server\u914D\u7F6E
server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    #\u901A\u8FC7eureka.client.register-with-eureka\uFF1Afalse\u548Cfetch-registry\uFF1Afalse\u6765\u8868\u660E\u81EA\u5DF1\u662F\u4E00\u4E2Aeureka server
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#\u914D\u7F6E\u670D\u52A1\u540D\u79F0 \u9700\u8981\u6307\u660Espring.application.name,\u8FD9\u4E2A\u5F88\u91CD\u8981
spring:
  application:
    name: eureka-server