#eureka-server配置
#8761 8762
server:
  port: 8761

#配置服务名称 需要指明spring.application.name,这个很重要
spring:
  application:
    name: eureka-server
  #profiles:
    #active: cluster1  #eureka集群部署注意修改这里

###eureka 单机配置
eureka:
  instance:
    hostname: localhost
  client:
    #通过eureka.client.register-with-eureka：false和fetch-registry：false来表明自己是一个eureka server
    register-with-eureka: false    #false表示不向注册中心注册自己。
    fetch-registry: false  #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#如果eureka需要集群部署达到高可用，则需要修改以下
#http://${eureka.instance.hostname}:${server.port}/eureka/ 有了集群需要写具体的ip
#修改原则如下：
#1.在任意一个eureka项目中，将上边这个地址修改为其他两个eureka项目的地址，中间用逗号隔开
#2.但是呢，这两个eureka项目的hostname还不能一样，不能全都是localhost，所以开发的时候，要在本地设置虚拟域名
#3.在windows下的C:\Windows\System32\drivers\etc\HOSTS文件最后添加如下
#    127.0.0.1 eureka1
#    127.0.0.1 eureka2
#这样，就可以将eureka项目中的hostname改为上边两个中的一个了

#集群配置 eureka1
---
spring:
  profiles: cluster1

eureka:
  instance:
    hostname: eureka1
  client:
    #通过eureka.client.register-with-eureka：false和fetch-registry：false来表明自己是一个eureka server
    register-with-eureka: false    #false表示不向注册中心注册自己。
    fetch-registry: false  #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka2:8762/eureka #这里设置除了自己之外另外N台eureka

#集群配置 eureka2
---
spring:
  profiles: cluster2

eureka:
  instance:
    hostname: eureka2
  client:
    #通过eureka.client.register-with-eureka：false和fetch-registry：false来表明自己是一个eureka server
    register-with-eureka: false    #false表示不向注册中心注册自己。
    fetch-registry: false  #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka1:8761/eureka #这里设置除了自己之外另外N台eureka

#启动集群注意修改端口和 spring:profiles.active: cluster