#8410  8412
server:
  port: 8410

spring:
  application:
    name: ribbon-service

#\u914D\u7F6E\u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/